name: upamakal
description: "UPamakal - Your Campus, Your Marketplace. A campus marketplace app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons for iOS-style widgets
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  
  # Google Sign In
  google_sign_in: ^6.2.2
  
  # Image Picker
  image_picker: ^1.1.2
  
  # Storage
  shared_preferences: ^2.3.2
  
  # State Management
  provider: ^6.1.2

  cloudinary_public: ^0.23.1
  http: ^1.2.0
  dio: ^5.4.0

  flutter_dotenv: ^5.1.0
  envied: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.0
  envied_generator: ^0.5.3

flutter:
  uses-material-design: true

  # Assets directory for logo and future images
  assets:
    - assets/images/
    - .env