// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdcc-QrgguGHWPd0V86jMpzNL_3I1rHZw',
    appId: '1:216383462965:web:c158c490fb0ee5fc4b9b7c',
    messagingSenderId: '216383462965',
    projectId: 'upamakal',
    authDomain: 'upamakal.firebaseapp.com',
    storageBucket: 'upamakal.firebasestorage.app',
    measurementId: 'G-7LDNSNPB0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6k5tDtnI25yJ9C4T21aWCYBn0GxTZzHI',
    appId: '1:216383462965:android:1bdcabfbc9ecd4f44b9b7c',
    messagingSenderId: '216383462965',
    projectId: 'upamakal',
    storageBucket: 'upamakal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXwaPgqKVE3KfwgOIuQXYLMlkZnEhidWk',
    appId: '1:216383462965:ios:f74f25678c3691f74b9b7c',
    messagingSenderId: '216383462965',
    projectId: 'upamakal',
    storageBucket: 'upamakal.firebasestorage.app',
    iosBundleId: 'com.example.upamakal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXwaPgqKVE3KfwgOIuQXYLMlkZnEhidWk',
    appId: '1:216383462965:ios:f74f25678c3691f74b9b7c',
    messagingSenderId: '216383462965',
    projectId: 'upamakal',
    storageBucket: 'upamakal.firebasestorage.app',
    iosBundleId: 'com.example.upamakal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdcc-QrgguGHWPd0V86jMpzNL_3I1rHZw',
    appId: '1:216383462965:web:2239abc1dd5c659e4b9b7c',
    messagingSenderId: '216383462965',
    projectId: 'upamakal',
    authDomain: 'upamakal.firebaseapp.com',
    storageBucket: 'upamakal.firebasestorage.app',
    measurementId: 'G-0J2XMX6TQT',
  );
}
